#!/bin/bash
echo -e "\n\e[1;47m General syntax:                                                     \e[0m\n"

echo -e "\\\e[\e[46;37mValue;Value;...\e[0mm\n"

echo -e "\e[1;47m Values:                                                             \e[0m\n"

echo -e "\e[1mBackground colors:\tForeground colors:\tStyles:\n"
echo -e "\e[40m \e[37mblack       \e[0m  \e[0m 40\t\e[40m \e[37mblack       \e[0m  \e[0m 30\tReset all   0"
echo -e "\e[41m \e[37mred         \e[0m  \e[0m 41\t\e[41m \e[37mred         \e[0m  \e[0m 31\t\e[1mBold   \e[0m     1/2"
echo -e "\e[42m \e[37mgreen       \e[0m  \e[0m 42\t\e[42m \e[37mgreen       \e[0m  \e[0m 32\t\e[3mItalic\e[0m      3"
echo -e "\e[43m \e[37myellow      \e[0m  \e[0m 43\t\e[43m \e[37myellow      \e[0m  \e[0m 33\t\e[4mUnderscore\e[0m  4"
echo -e "\e[44m \e[37mblue        \e[0m  \e[0m 44\t\e[44m \e[37mblue        \e[0m  \e[0m 34\t\e[5mBlink\e[0m       5/6"
echo -e "\e[45m \e[37mmagenta     \e[0m  \e[0m 45\t\e[45m \e[37mmagenta     \e[0m  \e[0m 35\t\e[7mReverse\e[0m     7"
echo -e "\e[46m \e[37mcyan        \e[0m  \e[0m 46\t\e[46m \e[37mcyan        \e[0m  \e[0m 36\t"
echo -e "\e[47m white       \e[0m   47\t\e[47m white       \e[0m   37\n"
