#!/usr/bin/zsh

j4-dmenu-desktop --dmenu="dmenu -i -nf '#000000' -nb '#FFFFFF' -sb '#FFFFFF' -sf '#FF0055' -h 23 -fn 'Inconsolata for Powerline-12'" --term="urxvtcd"

# Molokai
# j4-dmenu-desktop --dmenu="dmenu -i -nf '#101010' -nb '#D0D0D0' -sb '#D0D0D0' -sf '#FF4000' -h 23 -fn 'Inconsolata for Powerline-12'" --term="urxvtcd"
