#!/usr/bin/zsh

# Hemisu
j4-dmenu-desktop --dmenu="dmenu\
    -i \
    -x 460 -y 500 \
    -w 1000 -h 50 \
    -nb '#FF0055' \
    -sb '#FF0055' \
    -nf '#101010' \
    -sf '#FFFFFF' \
    -fn 'Inconsolata for Powerline-17'"

# Molokai
# j4-dmenu-desktop --dmenu="dmenu -i -nf '#101010' -nb '#D0D0D0' -sb '#D0D0D0' -sf '#FF4000' -h 23 -fn 'Inconsolata for Powerline-12'" --term="urxvtcd"
