#!/usr/bin/zsh


if [ -f /sys/class/power_supply/BAT1/capacity ]; then
    batt_status="$( cat /sys/class/power_supply/BAT1/status )"
    batt_capacity="$( cat /sys/class/power_supply/BAT1/capacity )"
    if [[ "$batt_status" == "Charging"  ]]; then
        echo "+$batt_capacity"
    elif [[ "$batt_status" == "Discharging"  ]]; then
        echo "-$batt_capacity"
    fi
else
    echo "~"
fi
