#!/bin/zsh

local hdmi_device="$( cat /sys/class/drm/card0-HDMI-A-1/status )"
local vga_device="$( cat /sys/class/drm/card0-VGA-1/status )"

case $1 in

    -w | --wait )
        if [ inotifywait -t 7200 "/sys/class/drm/card0-HDMI-A-1/status" ]; then
            case $hdmi_device in
                connected)
                    $HOME/.bin/toggle-monitor -l
                ;;
                disconnected)
                    $HOME/.bin/toggle-monitor -s
                ;;
            esac
        fi
        if [ inotifywait -t 7200 "/sys/class/drm/card0-VGA-1/status" ]; then
            case $hdmi_device in
                connected)
                    $HOME/.bin/toggle-monitor -l
                ;;
                disconnected)
                    $HOME/.bin/toggle-monitor -s
                ;;
            esac
        fi
    ;;

    -e | --exec )
        case $hdmi_device in
            connected)
                $HOME/.bin/toggle-monitor -l
                exit 0
            ;;
            disconnected)
                if [[ "$vga_device" == "connected" ]]; then
                    $HOME/.bin/toggle-monitor -l
                    exit 0
                else
                    $HOME/.bin/toggle-monitor -s
                    exit 0
                fi
            ;;
        esac
        case $vga_device in
            connected)
                $HOME/.bin/toggle-monitor -l
                exit 0
            ;;
            disconnected)
                if [[ "$hdmi_device" == "connected" ]]; then
                    $HOME/.bin/toggle-monitor -l
                    exit 0
                else
                    $HOME/.bin/toggle-monitor -s
                    exit 0
                fi
            ;;
        esac
    ;;

esac
